### ISSUE TITLE
Can you make this easier to install?

### ISSUE THREAD

**Issue by idogadol** [Tobi-Mob/Skul.Mod#1]
I really want to use your mod, I wish all of its features were in the base game;
but I have no idea how to build a .net project and every tutorial I watch feels too confusing to follow.

Could you make it more convenient to install? Just extracting files to the game's folder after installing BepInEx would be amazing.

**Comment by Tobi-Mob** [comment]
I was not sure if anybody would ever use this, so I did not really bother to make it easy :)
You are using Windows? You could try the below and tell me if that works. Then I could try to upload something easy.

`$(SkulDirectory)` would be the folder where the `Skul.exe` is. `C:\Program Files (x86)\Steam\steamapps\common\Skul` or something like that.

---------

Extract [BepInEx 6.0.0.549](https://builds.bepinex.dev/projects/bepinex_be/549/BepInEx_UnityMono_x64_f2c0e0f_6.0.0-be.549.zip) into `$(SkulDirectory)`

Extract [PlugIn.zip](https://github.com/Tobi-Mob/Skul.Mod/files/8066709/PlugIn.zip) into `$(SkulDirectory)`

Extract [Unstripped Unity files](https://unity.bepinex.dev/libraries/2020.1.17.zip) into `$(SkulDirectory)\Skul_Data\Managed\`

Download [UnitySetup64-2020.1.17f1.exe](https://download.unity3d.com/download_unity/9957aee8edc2/Windows64EditorInstaller/UnitySetup64-2020.1.17f1.exe)
Rename it to `setup.zip` and open it (if that does not work, try 7-zip)
Extract the content of `Editor\Data\MonoBleedingEdge\lib\mono\4.5\` into `$(SkulDirectory)\Skul_Data\Managed\`

---------

And that should be it. If the game is now started with Steam the mod should be loaded.
if the mod is running properly, pressing F1 and F2 while running around should display some text.
![image](https://user-images.githubusercontent.com/69400800/154015439-78894796-aeed-4d0c-9697-0989c430f361.png)

**Comment by idogadol** [comment]
**Thank you very much!**
It works, I hope either everyone uses your mod or all of its features & planned features will be put into the base game.
