### ISSUE TITLE
There's a "conflict" in the Installation Guide

### ISSUE THREAD

**Issue by lostone-zc** [Tobi-Mob/Skul.Mod#10]
In Unstrip Unity dlls part, the long description (guide by ghorsington) says I only need to download the file in this link: https://unity.bepinex.dev/corlibs/2020.3.22.zip , but in the short description, you say I should download the Unity and copy $(UnityDirectory)\Editor\Data\MonoBleedingEdge\lib\mono\4.5 

Is that same?

**Comment by Tobi-Mob** [comment]
Greetings,

No, they are not the same.

In the https://unity.bepinex.dev/corlibs/2020.3.22.zip download some files are missing (System.dll / mscorlib.dll / ...)
So I also needed to download the whole Unity-Editor to get the other files.

I tried stuff until the game no longer crashed and wrote all my steps down into a installation guide. So the guide is probably not optimal
If you can skip one step in the guide and still get it to run, that would be great to know!
Then I could change the install guide.

**Comment by lostone-zc** [comment]
System.dll and mscorlib.dll are inside the https://unity.bepinex.dev/corlibs/2020.3.22.zip
Maybe you misread it as https://unity.bepinex.dev/libraries/2020.3.22.zip ?

**Comment by lostone-zc** [comment]
Look like I wrote it unclearly, I mean the things except https://unity.bepinex.dev/libraries/2020.3.22.zip part(this part is required in both description)

**Comment by Tobi-Mob** [comment]
Ah I see now! I think you are right.
Seems like installing unity may not be necessary.

I will try that the next couple days if I have the time and will update the Docs if it works.

Thanks a lot.

**Comment by Tobi-Mob** [comment]
That worked. I changed the installation guide.
Thanks a lot for pointing that out!

The installation is now a lot easier.
