### ISSUE TITLE
Doesn't hook into the game

### ISSUE THREAD

**Issue by Ellura** [Tobi-Mob/Skul.Mod#13]
Installation keeps failing and my finger hurts from mashing the same button again and again for bossfights. Please help.

**Comment by Tobi-Mob** [comment]
Hi,

Did you have problems with any of the installation steps?
Are you on Windows?
After all the installation Steps, your Skul Folder should look a bit like this:
![image](https://user-images.githubusercontent.com/69400800/180637154-68c587ca-f872-4ed1-8de8-b3e91a763240.png)

What is your game doing? Does it start and Pressing F1 does nothing, or does it crash?

Installation Steps:
`$(SkulDirectory)` would be the folder where the Skul.exe is. 
For Windows it usually is: `C:\Program Files (x86)\Steam\steamapps\common\Skul` or something like that.

* Extract [Unstripped Unity files 2020.3.22 ](https://unity.bepinex.dev/libraries/2020.3.22.zip) into `$(SkulDirectory)\Skul_Data\Managed\`

* Extract [Unstripped corelibs 2020.3.22](https://unity.bepinex.dev/corlibs/2020.3.22.zip) into `$(SkulDirectory)\Skul_Data\Managed\`

* Extract [BepInEx 6.0.0.549](https://builds.bepinex.dev/projects/bepinex_be/549/BepInEx_UnityMono_x64_f2c0e0f_6.0.0-be.549.zip) into `$(SkulDirectory)`

* Extract [Skul.Mod.zip](https://github.com/Tobi-Mob/Skul.Mod/releases) into `$(SkulDirectory)`

* Run the game via Steam. If the mod is running correclty, pressing F1 while in the game will display a message above the player character.

**Comment by Tobi-Mob** [comment]
Feel free to reopen this issue, if you still have issues.

**Comment by Samvdg** [comment]
Hey Tobi, i actually have been having issues trying to get the mod to run.
I have done everything according to short and the full installation guide after the short one didnt work.
Ive even downgraded down to 1.5.2 but it still doesn't want to work.

This is my folder structure as the one you show in your screenshot in this issue:
![image](https://user-images.githubusercontent.com/42764788/196239223-0acf2a93-03fd-4c93-a63b-1eaeacbfea85.png)

I hope u can help me :)

**Comment by Samvdg** [comment]
@Tobi-Mob 
(i'd thought id mention you incase you have notifications for closed issues turned off)
