### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by ts2812ht** [Tobi-Mob/Skul.Mod#20]
New update for the game just come and the mod seem not working anymore
Can you update the mod pls

**Comment by Tobi-Mob** [comment]
Hi,

I put something together: https://github.com/Tobi-Mob/Skul.Mod/releases/tag/v1.0.3
The mod starts on my machine and the autoattack works. But I did not test any further.

So I can not guarantee that everything works, but I hope for the best.
