### ISSUE TITLE
Only drop common skull

### ISSUE THREAD

**Issue by Ikojin** [Tobi-Mob/Skul.Mod#27]
If I understood how the mod works, common skulls should drop in the first chapter, then rare, unique etc...
But for some reason all I drop is common skull, no mater the chapter.

Exemple in this photo, a common skull in the second chapter 
![Sans titre](https://user-images.githubusercontent.com/124004432/215617727-f52fbc44-d3fe-4278-b9b7-994130d145d7.png)

**Comment by Tobi-Mob** [comment]
Hi, that should hopefully be fixed now: 
https://github.com/Tobi-Mob/Skul.Mod/releases/tag/v1.0.4

If it still does not work with the newest release, you can open this issue again.
