### ISSUE TITLE
Common Skull issue

### ISSUE THREAD

**Issue by mkaler1574** [Tobi-Mob/Skul.Mod#28]
Just wanted to bring this to light in case the dev actually checks these, this issue only persists in the dark mirror
The base game doesn't have this problem. I would imagine its due to the mirror floors having different ids, but I don't actually know enough about the game to confirm

**Comment by Tobi-Mob** [comment]
Hi, that should hopefully be fixed now: 
https://github.com/Tobi-Mob/Skul.Mod/releases/tag/v1.0.4

If it still does not work with the newest release, you can open this issue again.

> I would imagine its due to the mirror floors having different ids

Yea, that was pretty much the reason :)
